name: PluginInfo
description: List of plugins and their versions
version: 0.2
author: NateLogan
main: org.petricek.bukkit.plugininfo.PluginInfo
commands:
  pluginversion:
    description: List of plugins and their versions
    usage: /<command> - Displays plugins verions
    aliases: [plugv]