name: PluginInfo
description: List of plugins and their versions
version: 0.1.0
author: NateLogan
web: http://forums.bukkit.org/threads/15105/
main: org.petricek.bukkit.plugininfo.PluginInfo
commands:
  plugininfo:
    description: List of plugins and their versions
    usage: /<command> - Displays help with further instructions
    aliases: [plugi]